name: flutter_facades
description: Laravel-like facades and helper functions for Dart and Flutter applications.
version: 0.1.0
repository: https://github.com/pishguy/flutter_facades
homepage: https://github.com/pishguy/flutter_facades

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # No required dependencies for core

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0
